In [723]:
from urllib.request import urlretrieve
import zipfile
import pandas as pd
import numpy as np
import random

# data 읽기
users_cols = ['user_id', 'age', 'sex', 'occupation', 'zip_code']
users = pd.read_csv(
    'data/u.user', sep='|', names=users_cols, encoding='latin-1')

watch_cols = ['user_id', 'movie_id', 'watch_hist_time']
watches = pd.read_csv(
    'data/u.watch', sep='\t', names=watch_cols, encoding='latin-1')

search_cols = ['user', 'search_hist']
searches = pd.read_csv(
    'data/u.search', sep='\t', names=search_cols, encoding='latin-1')

# The movies file contains a binary feature for each genre.
genre_cols = [
    "genre_unknown", "Action", "Adventure", "Animation", "Children", "Comedy",
    "Crime", "Documentary", "Drama", "Fantasy", "Film-Noir", "Horror",
    "Musical", "Mystery", "Romance", "Sci-Fi", "Thriller", "War", "Western",
]
movies_cols = [
    'movie_id', 'title', 'release_date', "video_release_date", "imdb_url"
] + genre_cols
movies = pd.read_csv(
    'data/u.item', sep='|', names=movies_cols, encoding='latin-1')

# Since the ids start at 1, we shift them to start at 0.
# users["user_id"] = users["user_id"].apply(lambda x: str(x-1))
# movies["movie_id"] = movies["movie_id"].apply(lambda x: str(x-1))
movies["year"] = movies['release_date'].apply(lambda x: str(x).split('-')[-1])
# watches["movie_id"] = watches["movie_id"].apply(lambda x: str(x-1))
# watches["user_id"] = watches["user_id"].apply(lambda x: str(x-1))
# searches["user_id"] = searches["user"].apply(lambda x: str(x-1))

# example_age 추가
movies['example_age'] = (pd.to_datetime("now") - pd.to_datetime(movies['release_date']))\
            /np.timedelta64(1,'D') 

# normalize
def normalize_col(df,col_name):
    df[col_name] = (df[col_name] - df[col_name].min()) / (df[col_name].max() - df[col_name].min())
    return df

movies = normalize_col(movies,'example_age')
watches = normalize_col(watches,'watch_hist_time')


# data 합치기
data = watches.merge(movies, on='movie_id').merge(users, on='user_id')
data['user_id']=data['user_id'].astype(int)
data['movie_id']=data['movie_id'].astype(int)
data = data.set_index(['user_id']).sort_index()
data = data.reset_index()
data['movie_name']=data['title'].str[:-6] # 년도 부분 자르기


# occupation 인코딩
occupations = data["occupation"].unique().tolist()
occupations_encoded = {x: i for i, x in enumerate(occupations)}
occupationsencoded2occupations = {i: x for i, x in enumerate(occupations)}

# search history 인코딩
search_hists = searches["search_hist"].unique().tolist()
search_encoded = {x: i for i, x in enumerate(search_hists)}
searchencoded2search = {i: x for i, x in enumerate(search_hists)}

# 유저 인덱스 인코딩
user_ids = data["user_id"].unique().tolist()
user2user_encoded = {x: i for i, x in enumerate(user_ids)}
userencoded2user = {i: x for i, x in enumerate(user_ids)}

# 영화 인덱스 인코딩
movie_ids = data["movie_id"].unique().tolist()
movie2movie_encoded = {x: i for i, x in enumerate(movie_ids)}
movie_encoded2movie = {i: x for i, x in enumerate(movie_ids)}

# 영화 제목 인코딩
title_ids = data["title"].unique().tolist()
title2title_encoded = {x: i for i, x in enumerate(title_ids)}
title_encoded2title = {i: x for i, x in enumerate(title_ids)}

# 인코딩으로 바꾸기
data["user"] = data["user_id"].map(user2user_encoded)
data["movie"] = data["movie_id"].map(movie2movie_encoded)
data["title_d"] = data["title"].map(title2title_encoded)
searches["search_hist"] = searches["search_hist"].map(search_encoded)
data["occupation"] = data["occupation"].map(occupations_encoded)
# searches["search_hist"] = searches["search_hist"]
searches = normalize_col(searches,'search_hist')

watch_hist = data.groupby(['user'])['movie_id'].apply(list).reset_index()
search_hist = searches.groupby(['user'])['search_hist'].apply(list).reset_index()
watch_hist_time = data.groupby(['user'])['watch_hist_time'].apply(list).reset_index()
example_age = data.groupby(['user'])['example_age'].apply(list).reset_index()

user_video_list = data.pivot(index='user_id', columns='movie_id', values='movie').reset_index()
user_video_list.fillna(data["movie_id"].max()+1, inplace=True)

sample_data=data[['user','occupation','sex']]
sample_data=sample_data.reset_index()
sample_data = sample_data.drop('index',axis=1)
sample_data = sample_data.drop_duplicates()

user_movie_list = pd.merge(sample_data,watch_hist, how= 'left')
user_movie_list = pd.merge(user_movie_list,watch_hist_time, how='left')
user_movie_list = pd.merge(user_movie_list,search_hist, how='left')
user_movie_list = pd.merge(user_movie_list,example_age, how='left')
user_movie_list['search_hist'] = user_movie_list['search_hist'].apply(lambda x: x if type(x) is list else []) # NaN 처리
user_movie_list['predict_labels'] = user_movie_list['movie_id'].apply(lambda x: int(random.uniform(0,data["movie"].max()))) #label을 마지막 값으로..



train_data = user_movie_list[(user_movie_list.user >= 1)&
                                  (user_movie_list.user <= 5)]
test_data = user_movie_list[(user_movie_list.user >= 6)&
                                  (user_title_list.user <= 10)]





In [724]:
movies # 영화 정보 데이터

movie_id                                              title release_date  \
0         1                                   Toy Story (1995)  01-Jan-1995   
1         2                                   GoldenEye (2011)  01-Jan-2011   
2         3                                  Four Rooms (2020)  01-Jan-2020   
3         4                                  Get Shorty (1995)  01-Jan-1995   
4         5                                     Copycat (1998)  01-Jan-1998   
5         6  Shanghai Triad (Yao a yao yao dao waipo qiao) ...  01-Jan-1995   
6         7                              Twelve Monkeys (2018)  01-Jan-2018   
7         8                                        Babe (1995)  01-Jan-1995   
8         9                            Dead Man Walking (1995)  01-Jan-1995   
9        10                                 Richard III (1995)  22-Jan-1996   

   video_release_date                                           imdb_url  \
0                 NaN  http://us.imdb.com/M/title-exact?Toy%20Story%2...   
1                 NaN  http://us.imdb.com/M/title-exact?GoldenEye%20(...   
2                 NaN  http://us.imdb.com/M/title-exact?Four%20Rooms%...   
3                 NaN  http://us.imdb.com/M/title-exact?Get%20Shorty%...   
4                 NaN  http://us.imdb.com/M/title-exact?Copycat%20(1998)   
5                 NaN  http://us.imdb.com/Title?Yao+a+yao+yao+dao+wai...   
6                 NaN  http://us.imdb.com/M/title-exact?Twelve%20Monk...   
7                 NaN     http://us.imdb.com/M/title-exact?Babe%20(1995)   
8                 NaN  http://us.imdb.com/M/title-exact?Dead%20Man%20...   
9                 NaN  http://us.imdb.com/M/title-exact?Richard%20III...   

   genre_unknown  Action  Adventure  Animation  Children  ...  Horror  \
0              0       0          0          1         1  ...       0   
1              0       1          1          0         0  ...       0   
2              0       0          0          0         0  ...       0   
3              0       1          0          0         0  ...       0   
4              0       0          0          0         0  ...       0   
5              0       0          0          0         0  ...       0   
6              0       0          0          0         0  ...       0   
7              0       0          0          0         1  ...       0   
8              0       0          0          0         0  ...       0   
9              0       0          0          0         0  ...       0   

   Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western  year  \
0        0        0        0       0         0    0        0  1995   
1        0        0        0       0         1    0        0  2011   
2        0        0        0       0         1    0        0  2020   
3        0        0        0       0         0    0        0  1995   
4        0        0        0       0         1    0        0  1998   
5        0        0        0       0         0    0        0  1995   
6        0        0        0       1         0    0        0  2018   
7        0        0        0       0         0    0        0  1995   
8        0        0        0       0         0    0        0  1995   
9        0        0        0       0         0    1        0  1996   

   example_age  
0     1.000000  
1     0.359982  
2     0.000000  
3     1.000000  
4     0.879969  
5     1.000000  
6     0.079947  
7     1.000000  
8     1.000000  
9     0.957726  

[10 rows x 26 columns]

In [725]:
user_movie_list

user  occupation sex       movie_id  \
0     0           0   M  [10, 3, 9, 5]   
1     1           1   F         [2, 7]   
2     2           2   M         [3, 8]   
3     3           0   M            [8]   
4     4           1   F            [4]   
5     5           3   M            [6]   
6     6           4   M         [2, 8]   
7     7           4   M     [7, 10, 1]   
8     8           5   M            [1]   
9     9           6   M            [1]   

                                     watch_hist_time search_hist  \
0  [0.024163568773234202, 0.0, 0.2131350681536555...       [0.0]   
1         [0.007390688617454417, 0.1644538856434767]  [0.0, 1.0]   
2          [0.17919100725792175, 0.2091520623119136]       [0.5]   
3                                              [1.0]       [1.0]   
4                             [0.017923526287838557]          []   
5                               [0.1614887590724022]          []   
6          [0.4109134360063728, 0.17919100725792175]          []   
7  [0.20477075588599752, 0.1644538856434767, 0.03...       [0.0]   
8                               [0.4109134360063728]          []   
9                              [0.20069923880332802]          []   

                                         example_age  predict_labels  
0  [0.9577264264593144, 0.0, 1.0, 0.8799693352316...               4  
1          [0.3599824772752164, 0.07994743182564891]               0  
2                                         [0.0, 1.0]               5  
3                                              [1.0]               2  
4                                              [1.0]               0  
5                                              [1.0]               7  
6                          [0.3599824772752164, 1.0]               5  
7     [0.07994743182564891, 0.9577264264593144, 1.0]               4  
8                                              [1.0]               4  
9                                              [1.0]               0

In [726]:
train_data # train data

user  occupation sex movie_id                             watch_hist_time  \
1     1           1   F   [2, 7]  [0.007390688617454417, 0.1644538856434767]   
2     2           2   M   [3, 8]   [0.17919100725792175, 0.2091520623119136]   
3     3           0   M      [8]                                       [1.0]   
4     4           1   F      [4]                      [0.017923526287838557]   
5     5           3   M      [6]                        [0.1614887590724022]   

  search_hist                                example_age  predict_labels  
1  [0.0, 1.0]  [0.3599824772752164, 0.07994743182564891]               0  
2       [0.5]                                 [0.0, 1.0]               5  
3       [1.0]                                      [1.0]               2  
4          []                                      [1.0]               0  
5          []                                      [1.0]               7

In [727]:
test_data # test data

user  occupation sex    movie_id  \
6     6           4   M      [2, 8]   
7     7           4   M  [7, 10, 1]   
8     8           5   M         [1]   
9     9           6   M         [1]   

                                     watch_hist_time search_hist  \
6          [0.4109134360063728, 0.17919100725792175]          []   
7  [0.20477075588599752, 0.1644538856434767, 0.03...       [0.0]   
8                               [0.4109134360063728]          []   
9                              [0.20069923880332802]          []   

                                      example_age  predict_labels  
6                       [0.3599824772752164, 1.0]               5  
7  [0.07994743182564891, 0.9577264264593144, 1.0]               4  
8                                           [1.0]               4  
9                                           [1.0]               0

In [728]:
EMBEDDING_DIMS = 16
DENSE_UNITS = 64
DROPOUT_PCT = 0.0
ALPHA = 0.0
NUM_CLASSES=data["movie"].max() + 2
LEARNING_RATE = 0.003

In [729]:
import tensorflow as tf
class MaskedEmbeddingsAggregatorLayer(tf.keras.layers.Layer):
    def __init__(self, agg_mode='sum', **kwargs):
        super(MaskedEmbeddingsAggregatorLayer, self).__init__(**kwargs)

        if agg_mode not in ['sum', 'mean']:
            raise NotImplementedError('mode {} not implemented!'.format(agg_mode))
        self.agg_mode = agg_mode
    
    @tf.function
    def call(self, inputs, mask=None):
        masked_embeddings = tf.ragged.boolean_mask(inputs, mask)
        if self.agg_mode == 'sum':
            aggregated =  tf.reduce_sum(masked_embeddings, axis=1)
        elif self.agg_mode == 'mean':
            aggregated = tf.reduce_mean(masked_embeddings, axis=1)
        return aggregated
    
    def get_config(self):
        # this is used when loading a saved model that uses a custom layer
        return {'agg_mode': self.agg_mode}
    
class L2NormLayer(tf.keras.layers.Layer):
    def __init__(self, **kwargs):
        super(L2NormLayer, self).__init__(**kwargs)
    
    @tf.function
    def call(self, inputs, mask=None):
        if mask is not None:
            inputs = tf.ragged.boolean_mask(inputs, mask).to_tensor()
        return tf.math.l2_normalize(inputs, axis=-1)

    def compute_mask(self, inputs, mask):
        return mask

In [730]:
#---inputs
import tensorflow as tf
import datetime
import os
input_watch_hist = tf.keras.Input(shape=(None, ), name='watch_hist')
input_watch_hist_time = tf.keras.layers.Input(shape=(None,), name='watch_hist_time')
input_search_hist = tf.keras.layers.Input(shape=(None,), name='search_hist')
input_example_age = tf.keras.Input(shape=(None, ), name='example_age')
input_occupation = tf.keras.Input(shape=(None, ), name='occupation')


#--- layers
features_embedding_layer = tf.keras.layers.Embedding(input_dim=NUM_CLASSES, output_dim=EMBEDDING_DIMS, 
                                            mask_zero=True, trainable=True, name='features_embeddings')
labels_embedding_layer = tf.keras.layers.Embedding(input_dim=NUM_CLASSES, output_dim=EMBEDDING_DIMS, 
                                            mask_zero=True, trainable=True, name='labels_embeddings')

avg_embeddings = MaskedEmbeddingsAggregatorLayer(agg_mode='mean', name='aggregate_embeddings')

dense_1 = tf.keras.layers.Dense(units=DENSE_UNITS, name='dense_1')
dense_2 = tf.keras.layers.Dense(units=DENSE_UNITS, name='dense_2')
dense_3 = tf.keras.layers.Dense(units=DENSE_UNITS, name='dense_3')
l2_norm_1 = L2NormLayer(name='l2_norm_1')

dense_output = tf.keras.layers.Dense(NUM_CLASSES, activation=tf.nn.softmax, name='dense_output')

#--- features
features_embeddings = features_embedding_layer(input_watch_hist)
l2_norm_features = l2_norm_1(features_embeddings)
avg_features = avg_embeddings(l2_norm_features)

labels_watch_embeddings = labels_embedding_layer(input_watch_hist_time)
l2_norm_watched = l2_norm_1(labels_watch_embeddings)
avg_watched = avg_embeddings(l2_norm_watched)

labels_search_embeddings = labels_embedding_layer(input_search_hist)
l2_norm_searched = l2_norm_1(labels_search_embeddings)
avg_searched = avg_embeddings(l2_norm_searched)

labels_example_age_embeddings = labels_embedding_layer(input_example_age)
l2_norm_example_age = l2_norm_1(labels_example_age_embeddings)
avg_example_age = avg_embeddings(l2_norm_example_age)

labels_occupation_embeddings = labels_embedding_layer(input_occupation)
l2_norm_occupation = l2_norm_1(labels_occupation_embeddings)
avg__occupation = avg_embeddings(l2_norm_occupation)


print(avg_features)
print(avg_watched)
print(avg_searched)
print(avg_example_age)
print(input_occupation)

# 임베딩 벡터들 연결
concat_inputs = tf.keras.layers.Concatenate(axis=1)([avg_features,
                                                     avg_watched,
                                                     avg_searched,
                                                     avg_example_age,
#                                                      avg__occupation
                                                     ])
# Dense Layers
dense_1_features = dense_1(concat_inputs)
dense_1_relu = tf.keras.layers.ReLU(name='dense_1_relu')(dense_1_features)
dense_1_batch_norm = tf.keras.layers.BatchNormalization(name='dense_1_batch_norm')(dense_1_relu)

dense_2_features = dense_2(dense_1_relu)
dense_2_relu = tf.keras.layers.ReLU(name='dense_2_relu')(dense_2_features)
# dense_2_batch_norm = tf.keras.layers.BatchNormalization(name='dense_2_batch_norm')(dense_2_relu)

dense_3_features = dense_3(dense_2_relu)
dense_3_relu = tf.keras.layers.ReLU(name='dense_3_relu')(dense_3_features)
dense_3_batch_norm = tf.keras.layers.BatchNormalization(name='dense_3_batch_norm')(dense_3_relu)
outputs = dense_output(dense_3_batch_norm)

#Optimizer
optimiser = tf.keras.optimizers.Adam(learning_rate=LEARNING_RATE)

#--- prep model
model = tf.keras.models.Model(
    inputs=[input_watch_hist, 
            input_watch_hist_time, 
            input_search_hist,
            input_example_age,
#             input_occupation,
            ],
    outputs=[outputs]
)
logdir = os.path.join("logs", datetime.datetime.now().strftime("%Y%m%d-%H%M%S"))
tensorboard_callback = tf.keras.callbacks.TensorBoard(logdir, histogram_freq=1)
model.compile(optimizer=optimiser, loss='sparse_categorical_crossentropy', metrics=['acc'])

model.summary()

Tensor("aggregate_embeddings/PartitionedCall_210:0", shape=(None, 16), dtype=float32)
Tensor("aggregate_embeddings/PartitionedCall_211:0", shape=(None, 16), dtype=float32)
Tensor("aggregate_embeddings/PartitionedCall_212:0", shape=(None, 16), dtype=float32)
Tensor("aggregate_embeddings/PartitionedCall_213:0", shape=(None, 16), dtype=float32)
Tensor("occupation_35:0", shape=(None, None), dtype=float32)
Model: "functional_90"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
watch_hist (InputLayer)         [(None, None)]       0                                            
__________________________________________________________________________________________________
watch_hist_time (InputLayer)    [(None, None)]       0                                            
_____________________________________________________________________________

In [733]:
history = model.fit([tf.keras.preprocessing.sequence.pad_sequences(train_data['movie_id']),
           tf.keras.preprocessing.sequence.pad_sequences(train_data['watch_hist_time'], dtype=float),
           tf.keras.preprocessing.sequence.pad_sequences(train_data['search_hist'], dtype=float) + 1e-10,
           tf.keras.preprocessing.sequence.pad_sequences(train_data['example_age'], dtype=float),
#            tf.keras.preprocessing.sequence.pad_sequences(train_data['occupation'], dtype=float),
           ],train_data['predict_labels'].values,
           steps_per_epoch=1, epochs=50)




Epoch 1/50
1/1 [==============================] - 0s 1ms/step - loss: 2.6043 - acc: 0.0000e+00
Epoch 2/50
1/1 [==============================] - 0s 813us/step - loss: 1.8832 - acc: 0.4000
Epoch 3/50
1/1 [==============================] - 0s 869us/step - loss: 1.4275 - acc: 0.8000
Epoch 4/50
1/1 [==============================] - 0s 862us/step - loss: 1.1645 - acc: 0.8000
Epoch 5/50
1/1 [==============================] - 0s 1ms/step - loss: 1.0339 - acc: 0.8000
Epoch 6/50
1/1 [==============================] - 0s 798us/step - loss: 0.9253 - acc: 0.8000
Epoch 7/50
1/1 [==============================] - 0s 798us/step - loss: 0.8287 - acc: 0.8000
Epoch 8/50
1/1 [==============================] - 0s 1ms/step - loss: 0.7541 - acc: 0.8000
Epoch 9/50
1/1 [==============================] - 0s 991us/step - loss: 0.6930 - acc: 0.8000
Epoch 10/50
1/1 [==============================] - 0s 1ms/step - loss: 0.6272 - acc: 0.8000
Epoch 11/50
1/1 [==============================] - 0s 932us/step - loss: 

In [734]:
model.save("candidate_generation.h5")

In [736]:
pred = model.predict([tf.keras.preprocessing.sequence.pad_sequences(test_data['movie_id']),
           tf.keras.preprocessing.sequence.pad_sequences(test_data['watch_hist_time'], dtype=float),
           tf.keras.preprocessing.sequence.pad_sequences(test_data['search_hist'], dtype=float) + 1e-10,
           tf.keras.preprocessing.sequence.pad_sequences(test_data['example_age'], dtype=float)
           ])

In [812]:
pred

array([[0.29336834, 0.04786491, 0.04974975, 0.0461837 , 0.03925468,
        0.1660044 , 0.03538063, 0.18565534, 0.0401783 , 0.03369631,
        0.06266367],
       [0.60133904, 0.02413096, 0.02635473, 0.02696007, 0.02255511,
        0.07244242, 0.0199002 , 0.12746969, 0.02437289, 0.02061064,
        0.03386427],
       [0.49409124, 0.02328836, 0.04170062, 0.02645917, 0.01976839,
        0.03899139, 0.0163851 , 0.2709723 , 0.02157266, 0.01727821,
        0.02949255],
       [0.49409124, 0.02328836, 0.04170062, 0.02645917, 0.01976839,
        0.03899139, 0.0163851 , 0.2709723 , 0.02157266, 0.01727821,
        0.02949255]], dtype=float32)

In [813]:
# candidate generation: 
###### 각 user당 top-7개의 추천 데이터를 뽑아낸다.
N = 6
k = np.sort((-pred).argsort()[:,:N])
print(k)
k = k.flatten()
k[k>data["movie"].max()]=0
k = np.unique(k)


[[ 0  1  2  5  7 10]
 [ 0  2  3  5  7 10]
 [ 0  2  3  5  7 10]
 [ 0  2  3  5  7 10]]


In [814]:
k

array([0, 1, 2, 3, 5, 7])

In [815]:
### ranking

In [816]:
# load candidate_generation 
model = tf.keras.models.load_model(
    'candidate_generation.h5',
    custom_objects={
        'L2NormLayer':L2NormLayer,
        'MaskedEmbeddingsAggregatorLayer':MaskedEmbeddingsAggregatorLayer
    }
)

In [817]:
# movie_data = movies.copy()
movie_data = movies.set_index(['movie_id']).sort_index()
movie_data = movie_data.loc[k+1]

In [818]:
movie_data

title release_date  \
movie_id                                                                   
1                                          Toy Story (1995)  01-Jan-1995   
2                                          GoldenEye (2011)  01-Jan-2011   
3                                         Four Rooms (2020)  01-Jan-2020   
4                                         Get Shorty (1995)  01-Jan-1995   
6         Shanghai Triad (Yao a yao yao dao waipo qiao) ...  01-Jan-1995   
8                                               Babe (1995)  01-Jan-1995   

          video_release_date  \
movie_id                       
1                        NaN   
2                        NaN   
3                        NaN   
4                        NaN   
6                        NaN   
8                        NaN   

                                                   imdb_url  genre_unknown  \
movie_id                                                                     
1         http://us.imdb.com/M/title-exact?Toy%20Story%2...              0   
2         http://us.imdb.com/M/title-exact?GoldenEye%20(...              0   
3         http://us.imdb.com/M/title-exact?Four%20Rooms%...              0   
4         http://us.imdb.com/M/title-exact?Get%20Shorty%...              0   
6         http://us.imdb.com/Title?Yao+a+yao+yao+dao+wai...              0   
8            http://us.imdb.com/M/title-exact?Babe%20(1995)              0   

          Action  Adventure  Animation  Children  Comedy  ...  Horror  \
movie_id                                                  ...           
1              0          0          1         1       1  ...       0   
2              1          1          0         0       0  ...       0   
3              0          0          0         0       0  ...       0   
4              1          0          0         0       1  ...       0   
6              0          0          0         0       0  ...       0   
8              0          0          0         1       1  ...       0   

          Musical  Mystery  Romance  Sci-Fi  Thriller  War  Western  year  \
movie_id                                                                    
1               0        0        0       0         0    0        0  1995   
2               0        0        0       0         1    0        0  2011   
3               0        0        0       0         1    0        0  2020   
4               0        0        0       0         0    0        0  1995   
6               0        0        0       0         0    0        0  1995   
8               0        0        0       0         0    0        0  1995   

          example_age  
movie_id               
1            1.000000  
2            0.359982  
3            0.000000  
4            1.000000  
6            1.000000  
8            1.000000  

[6 rows x 25 columns]

In [819]:
ratings_cols = ['user_id', 'movie_id', 'rating', 'unix_timestamp']
ratings = pd.read_csv(
    'data/u.data', sep='\t', names=ratings_cols, encoding='latin-1')

In [820]:
ratings

user_id  movie_id  rating  unix_timestamp
0         1        10       3       881250949
1         2         2       3       891717742
2         1         3       1       878887116
3        10         1       2       880606923
4         9         1       1       886397596
5         8         1       4       884182806
6         1         9       2       881171488
7         2         7       5       891628467
8         3         8       3       886324817
9         1         5       3       883603013
10        5         4       2       879372434
11        3         3       5       879781125
12        7         2       5       876042340
13        6         6       3       891035994
14        8         7       3       888104457
15        7         8       3       879485318
16        8        10       5       879270459
17        4         8       2       879539794

In [838]:
new_data = new_movies.merge(ratings, on='movie_id') # rating 추가

genre_occurences = new_data[genre_cols].sum().to_dict()
genres_encoded = {x: i for i, x in enumerate(genre_cols)}

get_genres(new_data, genre_cols)

new_data = new_data[['movie_id', 'user_id', 'rating', 'unix_timestamp', 'all_genres']]
new_data['movie_type'] = np.where(new_data['rating'] >= 3, 'like', 'dislike') # 3보다 크면 like



In [842]:

genre_list = new_data.groupby(['user_id'])['all_genres'].unique().apply(list).reset_index()
genre_list['all_genres']=genre_list['all_genres'].apply(lambda x: list(set(','.join(x))) ) # 중복제거
genre_list['all_genres']=genre_list['all_genres'].apply(lambda x:[ x for x in x if x.isdigit() ])

new_data = pd.merge(new_data,genre_list, how='left')


TypeError: unhashable type: 'list'

In [841]:
new_data

movie_id  user_id  rating  unix_timestamp all_genres movie_type
0          1       10       2       880606923      3,4,5    dislike
1          1        9       1       886397596      3,4,5    dislike
2          1        8       4       884182806      3,4,5       like
3          2        2       3       891717742     1,2,16       like
4          2        7       5       876042340     1,2,16       like
5          3        1       1       878887116         16    dislike
6          3        3       5       879781125         16       like
7          4        5       2       879372434      1,5,8    dislike
8          5        1       3       883603013     6,8,16       like
9          7        2       5       891628467       8,15       like
10         7        8       3       888104457       8,15       like